[package]
name = "align3d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "align3d"
path = "src/lib.rs"

[[bin]]
name = "cli"
path = "src/bin/main.rs"

# [features]
# viz = [
#     "dep:vulkano",
#     "dep:vulkano-shaders",
#     "dep:vulkano-win",
#     "dep:winit",
#     "dep:bytemuck",
#     "dep:nalgebra-glm",
#     "dep:cgmath"
# ]

[dependencies]
ndarray = { version = "0.15.3", features = ["approx", "rayon"] }
ndarray-rand = "0.14.0"
nshare = { version = "0.9.0", features = ["ndarray", "nalgebra"] }
rand = "0.8.5"
nalgebra = "*"
num = "*"
ndarray-linalg = "0.12.0"
approx = "0.5.1"
clap = { version = "4.0.18", features = ["cargo"] }
image = "0.24.4"
serde = "1.0.117"
serde_derive = "1.0.117"
serde_json = "1.0.59"
ply-rs = "0.1.3"
vulkano = { version = "0.32.1", optional = false }
vulkano-shaders = { version = "0.32.0", optional = false }
vulkano-win = { version = "0.32.0", optional = false }
winit = { version = "0.27.5", optional = false }
bytemuck = { version = "1.12.3", optional = false }
nalgebra-glm = { version = "0.17.0", optional = false }
# align3d-derive = { version = "0.1.0", path = "align3d-derive" }
cgmath = { version = "0.18.0", optional = false }

[dev-dependencies]
rstest = "0.15.0"
test-temp-file = "0.1.2"
tempfile = "3.3.0"
criterion = "0.4"

[[test]]
name = "viz-point_cloud"
path = "tests/viz/test_point_cloud.rs"
harness = false
features = "viz"

[[test]]
name = "viz-window"
path = "tests/viz/test_window.rs"
harness = false

[[test]]
name = "icp"
path = "tests/test_icp.rs"
harness = false

[[bench]]
name = "bench_mesh"
harness = false

[[bench]]
name = "bench_bilateral"
harness = false
