[package]
name = "align3d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "align3d"
path = "src/lib.rs"

[[bin]]
name = "cli"
path = "src/bin/main.rs"

[features]
viz = ["dep:vulkano", "dep:vulkano-shaders", "dep:vulkano-win", "dep:winit", "dep:bytemuck", "dep:nalgebra-glm"]

[dependencies]
ndarray = {version = "0.15.3", features = ["approx"] }
ndarray-rand = "0.14.0"
nshare = { version = "0.9.0", features = ["ndarray", "nalgebra"]}
rand = "0.8.5"
nalgebra = "*"
num = "*"
ndarray-linalg = "0.12.0"
approx = "0.5.1"
clap = {version = "4.0.18", features = ["cargo"]}
image = "0.24.4"
serde = "1.0.117"
serde_derive = "1.0.117"
serde_json = "1.0.59"
ply-rs = "0.1.3"
vulkano = { version="0.32.1", optional=true }
vulkano-shaders = { version="0.32.0", optional=true }
vulkano-win = { version="0.32.0", optional=true }
winit = { version="0.27.5", optional=true }
bytemuck = { version="1.12.3", optional = true }
nalgebra-glm = { version="0.17.0", optional = true }
# align3d-derive = { version = "0.1.0", path = "align3d-derive" }

[dev-dependencies]
rstest = "0.15.0"
test-temp-file = "0.1.2"
tempfile = "3.3.0"
